### PR TITLE
Fixes for final AGS 3.5.0

### PR DESCRIPTION
**Pull request by ivan-mogilko**
1. Saved project in a 3.5.0 to upgrade & convert format.

2. Replaced use of `#ifver 3.5` with `#ifdef SCRIPT_API_v3507` for Screen/Camera functions. This way script will keep working if user switches to lower API in 3.5.0 game.

### CODE REVIEW

**Comment by dkrey** [comment]
Thanks for the heads up!
Oh, and happy holidays :)

**Comment by ivan-mogilko** [comment]
@dkrey , would you be able to make an actual release for this new version? We'd like to add one into 3.5.0 package.

**Comment by dkrey** [comment]
@ivan-mogilko Done 👍

**Comment by ivan-mogilko** [comment]
Thank you , added into 3.5.0 p1. :)

I noticed you sent me an invite to become a collaborator for this template, but idk if I will have anything else to add.

**Pull request merged**
